name: snap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  camera: ^0.11.2
  google_sign_in: ^7.1.1
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  uuid: ^4.5.1
  story_view: ^0.16.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/snap_logo.png
