// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzN-WlSYcPYuF4bLNaZEh_7zg5xEq0Njg',
    appId: '1:660215397058:web:fd1088bb6c91fdc059d95b',
    messagingSenderId: '660215397058',
    projectId: 'snap-82bb2',
    authDomain: 'snap-82bb2.firebaseapp.com',
    storageBucket: 'snap-82bb2.firebasestorage.app',
    measurementId: 'G-WM06FQR03V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-uH0s8XaJguLwaXX4nENDibAOl9fP28o',
    appId: '1:660215397058:android:0d90313f8d17f2e659d95b',
    messagingSenderId: '660215397058',
    projectId: 'snap-82bb2',
    storageBucket: 'snap-82bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6kHhNzmnx_3XBj4UnDwriYP8NPRTzAYM',
    appId: '1:660215397058:ios:300e3ca181eba3f259d95b',
    messagingSenderId: '660215397058',
    projectId: 'snap-82bb2',
    storageBucket: 'snap-82bb2.firebasestorage.app',
    iosBundleId: 'com.example.snap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6kHhNzmnx_3XBj4UnDwriYP8NPRTzAYM',
    appId: '1:660215397058:ios:300e3ca181eba3f259d95b',
    messagingSenderId: '660215397058',
    projectId: 'snap-82bb2',
    storageBucket: 'snap-82bb2.firebasestorage.app',
    iosBundleId: 'com.example.snap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzN-WlSYcPYuF4bLNaZEh_7zg5xEq0Njg',
    appId: '1:660215397058:web:668d7fe2bd07439559d95b',
    messagingSenderId: '660215397058',
    projectId: 'snap-82bb2',
    authDomain: 'snap-82bb2.firebaseapp.com',
    storageBucket: 'snap-82bb2.firebasestorage.app',
    measurementId: 'G-RMMFR12ZTG',
  );
}
